apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: '{{ .Values.gpuCount | default 0 }}'
    machine.openshift.io/memoryMb: '{{ .Values.memoryMb | default 65536 }}'
    machine.openshift.io/vCPU: '{{ .Values.vCPU | default 16 }}'
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.infraName }}
  name: {{ .Values.infraName }}-{{ .Values.name }}-{{ .Values.availabilityZone }}
  namespace: openshift-machine-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.infraName }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.infraName }}-{{ .Values.name }}-{{ .Values.availabilityZone }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.infraName }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: {{ .Values.infraName }}-{{ .Values.name }}-{{ .Values.availabilityZone }}
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          {{- if eq .Values.cloud "aws" }}
          kind: AWSMachineProviderConfig
          {{- else }}
          kind: AzureMachineProviderSpec
          {{- end }}
          {{- if eq .Values.cloud "aws" }}
          ami:
            id: {{ .Values.aws.ami | required "aws.ami is required" }}
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: {{ .Values.aws.volumeSize | default 1500 }}
              volumeType: {{ .Values.aws.volumeType | default "gp3" }}
          credentialsSecret:
            name: aws-cloud-credentials
          capacityReservationId: ''
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ .Values.infraName }}-worker-profile
          instanceType: {{ .Values.aws.instance }}
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: {{ .Values.availabilityZone }}
            region: {{ .Values.region }}
          securityGroups:
          - filters:
            - name: 'tag:Name'
              values:
              - {{ .Values.infraName }}-node
          - filters:
            - name: 'tag:Name'
              values:
              - {{ .Values.infraName }}-lb
          subnet:
            filters:
            - name: 'tag:Name'
              values:
              - {{ .Values.subnet | required "subnet is required" }}
          tags:
          - name: kubernetes.io/cluster/{{ .Values.infraName }}
            value: owned
          {{- if .Values.aws.tags }}
          {{- range .Values.aws.tags }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          {{- else }}
          - name: Stack
            value: project {{ .Values.infraName }}-cluster-{{ .Values.clusterGuid | default "unknown" }}
          - name: config
            value: openshift-cluster
          - name: guid
            value: {{ .Values.clusterGuid | default "unknown" }}
          - name: owner
            value: {{ .Values.clusterOwner | default "unknown" }}
          - name: uuid
            value: {{ .Values.clusterUuid | default "unknown" }}
          {{- end }}
          userDataSecret:
            name: worker-user-data
          {{- else if eq .Values.cloud "azure" }}
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: {{ .Values.azure.imageSku }}
            type: MarketplaceNoPlan
            version: {{ .Values.azure.imageVersion }}
          osDisk:
            diskSettings: {}
            diskSizeGB: 128
            managedDisk:
              securityProfile:
                diskEncryptionSet: {}
              storageAccountType: Premium_LRS
            osType: Linux
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          networkResourceGroup: {{ .Values.azure.networkResourceGroup }}
          publicLoadBalancer: {{ .Values.azure.loadBalancer }}
          userDataSecret:
            name: worker-user-data
          vnet: {{ .Values.azure.vNet }}
          securityProfile:
            settings: {}
          diagnostics: {}
          zone: {{ .Values.availabilityZone }}
          publicIP: false
          resourceGroup: {{ .Values.azure.resourceGroup }}
          location: {{ .Values.region }}
          vmSize: Standard_NC4as_T4_v3    
          acceleratedNetworking: true
          subnet: {{ .Values.subnet }}
          {{- end }}
      {{- if .Values.taints }}
      taints:
      {{- range .Values.taints }}
        - effect: {{ .effect }}
          key: {{ .key }}
          {{- if .value }}
          value: {{ .value }}
          {{- end }}
      {{- end }}
      {{- end }}